import type { OperationsSettings } from "../../types/operations";

interface Props { settings: OperationsSettings; onChange(create: (current: OperationsSettings) => OperationsSettings): void }
export default function ResourcesTab({ settings, onChange }: Props) {
  const addSpool = () => onChange((current) => { const id = crypto.randomUUID(); return { ...current, activeSpoolId: id, spools: [...current.spools, { id, name: "New spool", material: "PLA", color: "#38bdf8", remainingGrams: 1000, costPerKilogram: null, driedAt: null }] }; });
  return <div className="space-y-8">
    <section><div className="mb-3 flex items-center justify-between"><h3 className="text-xs font-bold uppercase text-gray-400">Filament inventory</h3><button type="button" onClick={addSpool} className="text-xs text-blue-400">Add spool</button></div>
      <div className="grid gap-3 md:grid-cols-2">{settings.spools.map((spool) => <div key={spool.id} className={`border p-3 ${settings.activeSpoolId === spool.id ? "border-blue-500" : "border-gray-800"}`}>
        <div className="flex gap-3"><input type="color" aria-label="Spool color" value={spool.color} onChange={(e) => onChange((current) => ({ ...current, spools: current.spools.map((item) => item.id === spool.id ? { ...item, color: e.target.value } : item) }))} className="h-9 w-9 bg-transparent" /><div className="min-w-0 flex-1"><input value={spool.name} onChange={(e) => onChange((current) => ({ ...current, spools: current.spools.map((item) => item.id === spool.id ? { ...item, name: e.target.value } : item) }))} className="w-full bg-transparent text-sm font-bold text-white outline-none" /><p className="text-xs text-gray-500">{spool.material}</p></div><button type="button" onClick={() => onChange((current) => ({ ...current, activeSpoolId: spool.id }))} className="text-xs text-blue-400">Use</button></div>
        <label className="mt-3 block text-[10px] text-gray-500">Remaining grams<input type="number" min="0" value={spool.remainingGrams} onChange={(e) => onChange((current) => ({ ...current, spools: current.spools.map((item) => item.id === spool.id ? { ...item, remainingGrams: Number(e.target.value) } : item) }))} className="mt-1 w-full border border-gray-800 bg-black px-2 py-1.5 font-mono text-gray-200" /></label>
      </div>)}</div>{settings.spools.length === 0 && <p className="text-xs text-gray-600">No spools have been added.</p>}</section>
    <section><h3 className="mb-3 text-xs font-bold uppercase text-gray-400">Maintenance</h3><div className="space-y-2">{settings.maintenance.map((task) => { const due = task.completedPrintHours >= task.intervalHours; return <div key={task.id} className="flex items-center gap-4 border border-gray-800 bg-[#181d2c] p-3"><div className="flex-1"><p className="text-sm text-gray-200">{task.name}</p><p className={`text-[10px] ${due ? "text-yellow-400" : "text-gray-600"}`}>{task.completedPrintHours.toFixed(1)} / {task.intervalHours} print hours</p></div><button type="button" onClick={() => onChange((current) => ({ ...current, maintenance: current.maintenance.map((item) => item.id === task.id ? { ...item, completedPrintHours: 0, lastCompletedAt: Date.now() } : item) }))} className="text-xs text-blue-400">Mark complete</button></div>; })}</div></section>
  </div>;
}
