import type { OperationsSettings } from "../../types/operations";

interface Props { settings: OperationsSettings; connected: boolean; hasActivePrint: boolean; onChange(create: (current: OperationsSettings) => OperationsSettings): void; onSendMacro(commands: string): void; onExportDiagnostics(): Promise<string | null> }
export default function ToolsTab({ settings, connected, hasActivePrint, onChange, onSendMacro, onExportDiagnostics }: Props) {
  const run = (name: string, commands: string, confirm: boolean) => { if (!confirm || window.confirm(`Run ${name}?\n\n${commands}`)) onSendMacro(commands); };
  return <div className="space-y-8">
    <section><h3 className="mb-3 text-xs font-bold uppercase text-gray-400">Printer macros</h3><div className="grid gap-2 sm:grid-cols-3">{settings.macros.map((macro) => <button key={macro.id} type="button" disabled={!connected || hasActivePrint} onClick={() => run(macro.name, macro.commands, macro.requiresConfirmation)} title={macro.commands} className="border border-gray-800 bg-[#181d2c] p-3 text-left text-xs text-gray-200 hover:border-blue-600 disabled:text-gray-700"><span className="block font-bold">{macro.name}</span><span className="mt-1 block truncate font-mono text-[9px] text-gray-600">{macro.commands.replaceAll("\n", " / ")}</span></button>)}</div></section>
    <section className="grid gap-5 md:grid-cols-2"><div><h3 className="mb-3 text-xs font-bold uppercase text-gray-400">Camera</h3><label className="flex items-center gap-2 text-xs text-gray-300"><input type="checkbox" checked={settings.camera.enabled} onChange={(e) => onChange((current) => ({ ...current, camera: { ...current.camera, enabled: e.target.checked } }))} />Enable local camera</label><input value={settings.camera.streamUrl} onChange={(e) => onChange((current) => ({ ...current, camera: { ...current.camera, streamUrl: e.target.value } }))} placeholder="http://camera.local/stream" className="mt-3 w-full border border-gray-700 bg-black px-3 py-2 text-xs text-white" />{settings.camera.enabled && settings.camera.streamUrl && <img src={settings.camera.streamUrl} alt="Printer camera" className="mt-3 aspect-video w-full border border-gray-800 bg-black object-contain" />}</div>
    <div><h3 className="mb-3 text-xs font-bold uppercase text-gray-400">Local dashboard</h3><label className="flex items-center gap-2 text-xs text-gray-300"><input type="checkbox" checked={settings.network.enabled} onChange={(e) => onChange((current) => ({ ...current, network: { ...current.network, enabled: e.target.checked } }))} />Enable local network monitoring</label><label className="mt-3 block text-[10px] text-gray-500">Port<input type="number" min="1024" max="65535" value={settings.network.port} onChange={(e) => onChange((current) => ({ ...current, network: { ...current.network, port: Number(e.target.value) } }))} className="mt-1 w-full border border-gray-700 bg-black px-3 py-2 text-white" /></label><p className="mt-2 text-[10px] text-gray-600">Read-only mode is enforced until authenticated remote control is implemented.</p></div></section>
    <section><h3 className="mb-3 text-xs font-bold uppercase text-gray-400">Support</h3><button type="button" onClick={() => void onExportDiagnostics()} className="border border-gray-700 px-4 py-2 text-xs text-blue-400">Export sanitized diagnostics</button></section>
  </div>;
}
