import { memo } from "react";
import { ArrowRight, FileCode2, FolderOpen, ListPlus, MoreVertical, UploadCloud, X } from "lucide-react";
import type { ParsedGcode } from "../types/gcode";
import type { RecentFileEntry } from "../types/settings";

interface Props { gcode: ParsedGcode | null; recentFiles: RecentFileEntry[]; staleRecentPath: string | null; isLoading: boolean; hasActivePrint: boolean; onChooseFile(): void; onOpenRecent(path: string): void; onRemoveRecent(path: string): void; onClearRecent(): void; onClearFile(): void; onQueueRecent(file: RecentFileEntry): void }

function formatFileSize(bytes: number): string { return bytes < 1024 * 1024 ? `${Math.max(1, Math.round(bytes / 1024))} KB` : `${(bytes / (1024 * 1024)).toFixed(1)} MB`; }
function formatOpened(timestamp: number): string { const date = new Date(timestamp); const today = new Date(); return date.toDateString() === today.toDateString() ? `Today, ${date.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}` : date.toLocaleDateString([], { month: "short", day: "numeric", year: date.getFullYear() === today.getFullYear() ? undefined : "numeric" }); }

function FilePanel({ gcode, recentFiles, staleRecentPath, isLoading, hasActivePrint, onChooseFile, onOpenRecent, onRemoveRecent, onClearRecent, onClearFile, onQueueRecent }: Props) {
  return <div className="flex min-h-0 flex-1 flex-col gap-3"><section className="panel-surface shrink-0 p-3"><div className="mb-3 flex items-center justify-between"><h2 className="text-xs font-semibold text-slate-200">Upload G-code</h2>{gcode && <button type="button" onClick={onClearFile} disabled={hasActivePrint} title="Close current file" aria-label="Close current file" className="text-slate-600 hover:text-slate-200 disabled:text-slate-800"><X size={14} /></button>}</div><button type="button" onClick={onChooseFile} disabled={isLoading || hasActivePrint} className="grid min-h-28 w-full place-items-center rounded border border-dashed border-[#2a3a4d] bg-[#0b151f] px-3 py-4 text-center hover:border-blue-500/60 disabled:cursor-not-allowed"><span><UploadCloud size={28} strokeWidth={1.5} className="mx-auto text-slate-400" /><span className="mt-3 block text-[10px] text-slate-300">{isLoading ? "Reading G-code..." : "Drag & drop G-code file here"}</span><span className="mt-1 block text-[10px] text-blue-400">or click to browse</span>{gcode && <span className="mt-2 block max-w-48 truncate font-mono text-[9px] text-emerald-400">{gcode.fileName}</span>}</span></button></section>
    <section className="panel-surface flex min-h-0 flex-1 flex-col overflow-hidden"><header className="flex items-center border-b border-[#1d2a3a] px-3 py-3"><h2 className="text-xs font-semibold text-slate-200">Recent Files</h2><button type="button" onClick={onClearRecent} disabled={recentFiles.length === 0} title="Clear recent files" aria-label="Clear recent files" className="ml-auto text-slate-600 hover:text-white disabled:text-slate-800"><MoreVertical size={15} /></button></header><div className="min-h-0 flex-1 overflow-y-auto">{recentFiles.map((file) => { const active = gcode?.filePath === file.path; const stale = staleRecentPath === file.path; return <div key={file.path} className={`group flex items-center gap-3 border-b border-[#172333] px-3 py-2.5 ${active ? "bg-blue-950/25" : "hover:bg-[#121f2d]"}`}><button type="button" onClick={() => onOpenRecent(file.path)} disabled={isLoading || hasActivePrint} title={file.path} className="flex min-w-0 flex-1 items-center gap-3 text-left disabled:opacity-40"><span className={`grid h-10 w-10 shrink-0 place-items-center rounded ${stale ? "bg-rose-950/40 text-rose-400" : active ? "bg-blue-600/25 text-blue-400" : "bg-[#142438] text-blue-500"}`}><FileCode2 size={21} strokeWidth={1.5} /></span><span className="min-w-0"><strong className="block truncate text-[11px] font-semibold text-slate-200">{file.name}</strong><span className="mt-1 block truncate text-[9px] text-slate-500">{stale ? "File unavailable" : formatOpened(file.lastOpenedAt)}</span><span className="mt-0.5 block font-mono text-[9px] text-slate-600">{formatFileSize(file.size)}</span></span></button><span className="hidden shrink-0 items-center gap-1 group-hover:flex"><button type="button" onClick={() => onQueueRecent(file)} disabled={hasActivePrint} title="Add to print queue" aria-label={`Add ${file.name} to print queue`} className="grid h-7 w-7 place-items-center text-blue-400 hover:bg-blue-950/50"><ListPlus size={14} /></button><button type="button" onClick={() => onRemoveRecent(file.path)} title="Remove from recent files" aria-label={`Remove ${file.name} from recent files`} className="grid h-7 w-7 place-items-center text-slate-600 hover:text-rose-400"><X size={13} /></button></span></div>; })}{recentFiles.length === 0 && <div className="grid h-32 place-items-center px-5 text-center text-[10px] text-slate-600">Recently opened G-code files will appear here.</div>}</div><button type="button" onClick={onChooseFile} disabled={isLoading || hasActivePrint} className="flex shrink-0 items-center gap-2 border-t border-[#1d2a3a] px-3 py-3 text-[10px] text-slate-300 hover:bg-[#121f2d] disabled:text-slate-700"><FolderOpen size={14} /><span>Browse all files</span><ArrowRight size={14} className="ml-auto" /></button></section>
  </div>;
}

export default memo(FilePanel);
